#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/.dotfiles

# your project folder that we can `c [tab]` to
export WORKSPACE=~/workspace

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# all of our zsh files
typeset -U config_files
config_files=($DOTFILES/*/*.zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# load everything but the path and completion files
for file in ${config_files:#(*oh-my-zsh*|*prezto*|*powerline*|*/path.zsh|*/completion.zsh)}
do
  source $file
done

# initialize autocomplete here, otherwise functions won't be loaded
# this is done in modules/completion/init.zsh
#zmodload -i zsh/complist
#autoload -U compinit
#compinit

# load every completion after autocomplete loads
for file in ${${(M)config_files:#*/completion.zsh}:#*oh-my-zsh*}
do
  source $file
done

# don't know who the heck is setting this..
unset GREP_OPTIONS

# source bashrc if available, for bash compatibility
if [[ -a ~/.bashrc ]]
then
  source ~/.bashrc
fi

# load gradle autocompleteion
[[ -d ~/.zsh/gradle-completion ]] && fpath=(~/.zsh/gradle-completion $fpath)

unset config_files

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

export PATH=$PATH:/home/konstantin/.spicetify
